### ISSUE TITLE
npm run app:preview 以及 build 打开空白

### ISSUE THREAD

**Issue by InCodingNowLiu** [Yukun-Guo/vite-vue3-electron-ts-template#3]

**Comment by Yukun-Guo** [comment]
@InCodingNowLiu 你可以具体地描述一下问题吗？ 或者截图develop tools中Console的内容，帮助我更好的定位问题。谢谢！

**Comment by Yukun-Guo** [comment]
@InCodingNowLiu I think I got your point. This is a bug of electron on MacOS. Unfortunately, this bug hasn't been fixed in the latest version. I will keep eye on it. Please follow this [issue](https://github.com/electron/electron/issues/33685) for the latest progress.

**Comment by FiShelly** [comment]
may be you can use loadFile in production mode or use url to parse path.

```
// and load the index.html of the app.
    isDev ? mainWindow.loadURL(
        'http://localhost:3000'
    ) : mainWindow.loadFile(join(__dirname, '../../index.html'));
// other way
mainWindow.loadURL(
        isDev ? 'http://localhost:3100' : url.format({
            protocol: 'file',
            slashes: true,
            pathname: join(__dirname, '../../index.html')
        })
    );
```

**Comment by Yukun-Guo** [comment]
@FiShelly Thanks! It works. I'm closing this issue now.
