### ISSUE TITLE
路由组件（Home或者About）使用img标签引用资源Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by KurosakiRei** [Yukun-Guo/vite-vue3-electron-ts-template#5]
构建的程序在使用命令`npm run app:dev`时没有任何问题，但使用`npm run app:preview`和`npm run app:build`时就会产生`Failed to load resource: net::ERR_FILE_NOT_FOUND`

`npm run app:dev`
![image](https://user-images.githubusercontent.com/36018774/231172644-be21a234-0116-4bd9-98c4-c49a7d3f96c1.png)
`npm run app:preview`
![image](https://user-images.githubusercontent.com/36018774/231173566-54380d5a-5bcd-4f95-bed7-9d7cd2f9d7c2.png)

**Comment by Yukun-Guo** [comment]
感谢发现并反馈这个bug，
修改 vite.config.ts 的 base path 並不能解決这个问题。我在最新的版本中修复了这个bug，请查阅
https://github.com/Yukun-Guo/vite-vue3-electron-ts-template

Best,
Yukun

**Comment by KurosakiRei** [comment]
实在不好意思，其实我已经把问题解决了，所以我就擅自把问题给关了并没有给说明，`Failed to load resource: net::ERR_FILE_NOT_FOUND`的主要原因是`vue-router`的工作模式有问题，只要调成`hash mode`就好了。因为程序打包后的浏览器用的协议是`file://`
![image](https://user-images.githubusercontent.com/36018774/231587361-6a4553f5-12a4-43ed-b3c9-a6c99841eb10.png)

PS: 这个模板很好用，十分感谢

**Comment by Yukun-Guo** [comment]
这个问题的解决方式看样子不止一种，多谢反馈！
