### ISSUE TITLE
Save the error in router.js

### ISSUE THREAD

**Issue by cdxhkj** [Yukun-Guo/vite-vue3-electron-ts-template#6]
1. app:dev     // success
2. Save the error in router.js
3. 
![image](https://github.com/Yukun-Guo/vite-vue3-electron-ts-template/assets/128960659/1b677db6-8a8a-4e93-b823-f3fe078e16e3)
[0] 17:55:34 [vite] Internal server error: URI malformed
[0]       at decodeURI (<anonymous>)
[0]       at viteTransformMiddleware (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:57512:19)
[0]       at call (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44131:7)
[0]       at next (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44075:5)
[0]       at D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:49249:28
[0]       at viteServePublicMiddleware (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:49761:9)
[0]       at call (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44131:7)
[0]       at next (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44075:5)
[0]       at next (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44053:14)
[0]       at next (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44053:14)

**Comment by jackzhujie** [comment]
I have the same problem

**Comment by jackzhujie** [comment]
I solved this problem by simply adding the default path '/' to router/index.ts, which I redirect to the '/home' page.
The modified code is as follows：
```javascript
import { createRouter, RouteRecordRaw, createWebHashHistory} from "vue-router";
import Home from "../components/Home.vue";
import About from "../components/About.vue";

const routes: RouteRecordRaw[] = [
    {
        path: "/",
        name: "index",
        redirect: "/home"
    },
    {
        path: "/home",
        name: "Home",
        component: Home,
    },
    {
        path: "/about",
        name: "About",
        component: About,
    },
];

const router = createRouter({
    history: createWebHashHistory(),
    routes,
});

export default router;
```

**Comment by Sanel-Trnka** [comment]
> 1. app:dev     // success
> 2. Save the error in router.js
> 
> ![image](https://user-images.githubusercontent.com/128960659/241187579-1b677db6-8a8a-4e93-b823-f3fe078e16e3.png) [0] 17:55:34 [vite] Internal server error: URI malformed [0] at decodeURI () [0] at viteTransformMiddleware (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:57512:19) [0] at call (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44131:7) [0] at next (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44075:5) [0] at D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:49249:28 [0] at viteServePublicMiddleware (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:49761:9) [0] at call (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44131:7) [0] at next (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44075:5) [0] at next (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44053:14) [0] at next (D:\Workbench\vite-vue3-electron-ts-template\node_modules\vite\dist\node\chunks\dep-689425f3.js:44053:14)

I've faced the same problem and after some trying I found the problem: 

In the "index.html" in the root directory, you find following lines of code:

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <base href="<%= BASE_URL %>">
  <link rel="icon" href="/favicon.ico" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vite App</title>
</head>

<body>
  <div id="app"></div>
  <script type="module" src="/src/main.ts"></script>
</body>

</html>
```

This line is the problem:

`<base href="<%= BASE_URL %>"> `

This adds the string in front of any route, and during reload it cant properly resolve the path so it throws the error. So when clicking on "About", it shows following link: 

`http://localhost:3000/%3C%=%20BASE_URL%20%%3E/about `

Try removing the line, did it for me at least. :)

**Comment by Yukun-Guo** [comment]
Thank you @Sanel-Trnka. Your solution can fix this issue in Vue, but it causes path issues in electron. The `<base href="<%= BASE_URL %>">` makes the route load image in electron correctly. For this issue, I set "server.hmr.overlay:false" in vite.config.ts to prevent the error in electron.
