### ISSUE TITLE
Use FS in electron app

### ISSUE THREAD

**Issue by schplitt** [Yukun-Guo/vite-vue3-electron-ts-template#7]
Hello Yukun,

I'm using your template to build my own app.
I am still new to electron and I need to access files and save them.

I was wondering if you were willing to help me or give me resources to get FS up and running inside the app.

So the "error" is that even though the app is rendered in a window, it still thinks that it is running inside a browser and not using nodejs.
Do you have any ideas on how to fix this? I assume it has something to do with vite?

Thank you very much in advance
Jakob

**Comment by Yukun-Guo** [comment]
Hi Jakob,

I added a demo of how to use FS to the latest version. You can learn more from the [official documents](https://www.electronjs.org/docs/latest/tutorial/ipc#pattern-2-renderer-to-main-two-way). Hope this can help!

Yukun

**Comment by schplitt** [comment]
Hello Yukun,

I was completely unaware of how electron works internally.

Thank you very much for taking the time.
I wish you the best of luck on your degree!

Cheers,
Jakob
